"""
Django settings for atic project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import logging
from collections import OrderedDict
from pathlib import Path
import os
import dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(int(os.environ.get("DEBUG", "0")))

ALLOWED_HOSTS = ['*']
CSRF_TRUSTED_ORIGINS = ['http://localhost:8000',
                        "http://127.0.0.1:8000", "http://atic.com:8000", "http://atic:8000", os.environ.get("CSRF_IP")]
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'django_filters',
    'constance',
    "constance.backends.database",
    'backend',
    "phonenumber_field",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'atic.urls'

LOG_FILE_NAME = "../{0}" if DEBUG else "/ATIC-LOGS/{0}"
LOGGING = {
    "version": 1,
    "filters": {
        "debug": {
            "()": "django.utils.log.RequireDebugTrue"
        },
        "prod": {
            "()": "django.utils.log.RequireDebugFalse"
        }
    },
    "formatters": {
        "verbose": {
            "format": "{asctime} - {module} - {thread:d} - {message}",
            "style": "{"
        },
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "filters": ["debug"]

        },
        "file_info": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filters": ["prod"],
            "filename": LOG_FILE_NAME.format("info.log")
        },
        "file_error": {
            "level": "ERROR",
            "class": "logging.FileHandler",
            "formatter": "verbose",
            "filename": LOG_FILE_NAME.format("error.log")
        }
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "atic.errors": {
            "handlers": ["file_error", "console"],
            "level": "ERROR",
            "propagate": False
        },
        "atic.info": {
            "handlers": ["file_info"],
            "level": "INFO",

            "propagate": False
        }
    }
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'constance.context_processors.config',
                'django.contrib.messages.context_processors.messages',

            ],
        },
    },
]

WSGI_APPLICATION = 'atic.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get("DATABASE"),
        'USER': os.environ.get("USER"),
        'PASSWORD': os.environ.get("PASSWORD"),
        'HOST': os.environ.get("HOST", "mysql_db"),
        'PORT': os.environ.get("PORT", '3306')
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'es-cr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'

STATIC_ROOT = os.path.join(BASE_DIR, "static/")
MEDIA_ROOT = os.path.join(BASE_DIR, "media/")
# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = "/login"

LOGOUT_REDIRECT_URL = "/"

LOGIN_REDIRECT_URL = "plaqueados"
# Constance settings

CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'

CONSTANCE_CONFIG = OrderedDict({
    'TITULO_ENCARGADO_BIENES': ("Sra", "Titulo de encargad@ de bienes"),
    'NOMBRE_ENCARGADO_BIENES': ("Yontil Villalobos Mora", "Nombre de encargad@ de bienes"),
    'CARGO_ENCARGADO_BIENES': ("Encargada de Bienes Institucionales", "Cargo de encargad@ de bienes"),

    "TITULO_ATIC": ("V°B° M.C.I", "Titulo de encargad@ atic"),
    "NOMBRE_ATIC": ("Julio Rayo", "Nombre de encargad@ atic"),
    "CARGO_ATIC": ("Encargado ATIC", "Cargo de encargad@ atic"),
})

CORS_ALLOWED_ORIGINS = [
    'http://localhost:3030',
]

# Phone Number

PHONENUMBER_DEFAULT_REGION = "CR"
