# Generated by Django 4.0.4 on 2023-02-11 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=120)),
                ('nombre_completo', models.CharField(max_length=120, unique=True)),
                ('correo_institucional', models.CharField(blank=True, max_length=120, null=True)),
                ('correo_personal', models.CharField(blank=True, max_length=120, null=True)),
                ('telefono_oficina', models.CharField(blank=True, max_length=120, null=True)),
                ('telefono_personal', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'verbose_name_plural': 'Funcionarios',
            },
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('lectura', 'puede ingresar a las vistas'), ('escritura', 'puede manipular datos por medio de las vistas'), ('respaldos', 'puede respaldar la base de datos')],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=230, unique=True)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Red',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MAC', models.CharField(max_length=45, unique=True)),
                ('IP', models.CharField(blank=True, default='', max_length=20)),
                ('IP6', models.CharField(blank=True, default='', max_length=40)),
                ('IP_switch', models.CharField(blank=True, default='', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Subtipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('detalle', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('detalle', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tramites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=120, unique=True)),
                ('tipo', models.CharField(choices=[(None, '--------'), ('Traslado', 'Traslado'), ('Deshecho', 'Deshecho'), ('Taller', 'Taller')], default='Traslado', max_length=12)),
                ('detalles', models.CharField(max_length=900)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[(None, '--------'), ('Pendiente', 'Pendiente'), ('Finalizado', 'Finalizado'), ('En Proceso', 'En Proceso'), ('Aceptado', 'Aceptado')], default='Pendiente', max_length=12)),
                ('recipiente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='backend.funcionarios')),
                ('remitente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='backend.funcionarios')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('coordinador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.funcionarios')),
            ],
        ),
        migrations.CreateModel(
            name='Ubicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(default='NA', max_length=120, unique=True)),
                ('instalacion', models.CharField(choices=[(None, '--------'), ('Esparza', 'Instalación de Esparza'), ('Cocal', 'Instalación del Cocal')], default='Esparza', max_length=10)),
                ('custodio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.funcionarios')),
                ('unidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.unidad')),
            ],
            options={
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='Traslados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(default='', max_length=120)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='backend.ubicaciones')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.tramites')),
            ],
            options={
                'verbose_name_plural': 'Traslados',
            },
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.CharField(max_length=200)),
                ('beneficiario', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.tramites')),
            ],
        ),
        migrations.CreateModel(
            name='Deshecho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.tramites')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('numero_orden_compra', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('numero_solicitud', models.CharField(blank=True, max_length=150)),
                ('origen_presupuesto', models.CharField(blank=True, max_length=200)),
                ('decision_inicial', models.CharField(blank=True, max_length=100)),
                ('numero_procedimiento', models.CharField(blank=True, max_length=120)),
                ('numero_factura', models.CharField(blank=True, max_length=120)),
                ('detalle', models.CharField(blank=True, max_length=300)),
                ('informe_tecnico', models.CharField(blank=True, max_length=120)),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Activos_Plaqueados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.CharField(blank=True, max_length=300, null=True)),
                ('nombre', models.CharField(max_length=120)),
                ('marca', models.CharField(max_length=200)),
                ('valor', models.CharField(max_length=200, null=True)),
                ('modelo', models.CharField(max_length=200)),
                ('serie', models.CharField(max_length=200, null=True)),
                ('garantia', models.DateField(null=True)),
                ('fecha_ingreso', models.DateField(null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[(None, '--------'), ('Deshecho', 'Deshecho'), ('En uso', 'En uso'), ('Funcional', 'Funcional'), ('Obsoleto', 'Obsoleto'), ('Obsoleto en revision', 'Obsoleto en revision'), ('Obsoleto en uso', 'Obsoleto en uso'), ('Obsoleto en repuesto', 'Obsoleto en repuesto'), ('Optimo', 'Optimo'), ('Proceso de deshecho', 'Proceso de deshecho'), ('Uso academico', 'Uso academico')], default='Optimo', max_length=25)),
                ('placa', models.CharField(max_length=30)),
                ('compra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.compra')),
                ('red', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.red')),
                ('subtipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.subtipo')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.tipo')),
                ('tramites', models.ManyToManyField(to='backend.tramites')),
                ('ubicacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.ubicaciones')),
                ('ubicacion_anterior', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='plaqueados', to='backend.ubicaciones')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Activos_No_Plaqueados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.CharField(blank=True, max_length=300, null=True)),
                ('nombre', models.CharField(max_length=120)),
                ('marca', models.CharField(max_length=200)),
                ('valor', models.CharField(max_length=200, null=True)),
                ('modelo', models.CharField(max_length=200)),
                ('serie', models.CharField(max_length=200, null=True)),
                ('garantia', models.DateField(null=True)),
                ('fecha_ingreso', models.DateField(null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[(None, '--------'), ('Deshecho', 'Deshecho'), ('En uso', 'En uso'), ('Funcional', 'Funcional'), ('Obsoleto', 'Obsoleto'), ('Obsoleto en revision', 'Obsoleto en revision'), ('Obsoleto en uso', 'Obsoleto en uso'), ('Obsoleto en repuesto', 'Obsoleto en repuesto'), ('Optimo', 'Optimo'), ('Proceso de deshecho', 'Proceso de deshecho'), ('Uso academico', 'Uso academico')], default='Optimo', max_length=25)),
                ('compra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.compra')),
                ('red', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.red')),
                ('subtipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.subtipo')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.tipo')),
                ('tramites', models.ManyToManyField(to='backend.tramites')),
                ('ubicacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.ubicaciones')),
                ('ubicacion_anterior', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='no_plaqueados', to='backend.ubicaciones')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
