# Generated by Django 4.0.4 on 2023-07-11 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='nombre',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='activos_no_plaqueados',
            name='compra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.compra', verbose_name='Compra'),
        ),
        migrations.AlterField(
            model_name='activos_no_plaqueados',
            name='estado',
            field=models.CharField(choices=[(None, '--------'), ('Deshecho', 'Deshecho'), ('En uso', 'En uso'), ('Funcional', 'Funcional'), ('Obsoleto', 'Obsoleto'), ('Obsoleto en revision', 'Obsoleto en revision'), ('Obsoleto en uso', 'Obsoleto en uso'), ('Obsoleto en repuesto', 'Obsoleto en repuesto'), ('Optimo', 'Optimo'), ('Proceso de deshecho', 'Proceso de deshecho'), ('Uso academico', 'Uso academico')], default='Optimo', max_length=25, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='activos_no_plaqueados',
            name='fecha_ingreso',
            field=models.DateField(null=True, verbose_name='Fecha de Ingreso'),
        ),
        migrations.AlterField(
            model_name='activos_no_plaqueados',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='activos_no_plaqueados',
            name='garantia',
            field=models.DateField(null=True, verbose_name='Garantia'),
        ),
        migrations.AlterField(
            model_name='activos_no_plaqueados',
            name='marca',
            field=models.CharField(max_length=200, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='activos_no_plaqueados',
            name='modelo',
            field=models.CharField(max_length=200, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='activos_no_plaqueados',
            name='nombre',
            field=models.CharField(max_length=120, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='activos_no_plaqueados',
            name='observacion',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Observación'),
        ),
        migrations.AlterField(
            model_name='activos_no_plaqueados',
            name='red',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.red', verbose_name='Red'),
        ),
        migrations.AlterField(
            model_name='activos_no_plaqueados',
            name='serie',
            field=models.CharField(max_length=200, null=True, verbose_name='Serie'),
        ),
        migrations.AlterField(
            model_name='activos_no_plaqueados',
            name='subtipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.subtipo', verbose_name='Subtipo'),
        ),
        migrations.AlterField(
            model_name='activos_no_plaqueados',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.tipo', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='activos_no_plaqueados',
            name='tramites',
            field=models.ManyToManyField(to='backend.tramites', verbose_name='Tramites'),
        ),
        migrations.AlterField(
            model_name='activos_no_plaqueados',
            name='ubicacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.ubicaciones', verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='activos_no_plaqueados',
            name='valor',
            field=models.CharField(max_length=200, null=True, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='activos_plaqueados',
            name='compra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.compra', verbose_name='Compra'),
        ),
        migrations.AlterField(
            model_name='activos_plaqueados',
            name='estado',
            field=models.CharField(choices=[(None, '--------'), ('Deshecho', 'Deshecho'), ('En uso', 'En uso'), ('Funcional', 'Funcional'), ('Obsoleto', 'Obsoleto'), ('Obsoleto en revision', 'Obsoleto en revision'), ('Obsoleto en uso', 'Obsoleto en uso'), ('Obsoleto en repuesto', 'Obsoleto en repuesto'), ('Optimo', 'Optimo'), ('Proceso de deshecho', 'Proceso de deshecho'), ('Uso academico', 'Uso academico')], default='Optimo', max_length=25, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='activos_plaqueados',
            name='fecha_ingreso',
            field=models.DateField(null=True, verbose_name='Fecha de Ingreso'),
        ),
        migrations.AlterField(
            model_name='activos_plaqueados',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='activos_plaqueados',
            name='garantia',
            field=models.DateField(null=True, verbose_name='Garantia'),
        ),
        migrations.AlterField(
            model_name='activos_plaqueados',
            name='marca',
            field=models.CharField(max_length=200, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='activos_plaqueados',
            name='modelo',
            field=models.CharField(max_length=200, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='activos_plaqueados',
            name='nombre',
            field=models.CharField(max_length=120, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='activos_plaqueados',
            name='observacion',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Observación'),
        ),
        migrations.AlterField(
            model_name='activos_plaqueados',
            name='red',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.red', verbose_name='Red'),
        ),
        migrations.AlterField(
            model_name='activos_plaqueados',
            name='serie',
            field=models.CharField(max_length=200, null=True, verbose_name='Serie'),
        ),
        migrations.AlterField(
            model_name='activos_plaqueados',
            name='subtipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.subtipo', verbose_name='Subtipo'),
        ),
        migrations.AlterField(
            model_name='activos_plaqueados',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.tipo', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='activos_plaqueados',
            name='tramites',
            field=models.ManyToManyField(to='backend.tramites', verbose_name='Tramites'),
        ),
        migrations.AlterField(
            model_name='activos_plaqueados',
            name='ubicacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.ubicaciones', verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='activos_plaqueados',
            name='valor',
            field=models.CharField(max_length=200, null=True, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='tramite',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='taller', to='backend.tramites'),
        ),
        migrations.AlterField(
            model_name='traslados',
            name='tramite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traslados', to='backend.tramites'),
        ),
    ]
