# Generated by Django 4.2.7 on 2024-05-17 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relpruebasapi',
            name='dato4',
        ),
        migrations.DeleteModel(
            name='PruebasAPI',
        ),
        migrations.DeleteModel(
            name='RelPruebasAPI',
        ),
    ]
