# Generated by Django 4.2.7 on 2024-07-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activos_no_plaqueados',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='activos_plaqueados',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de Registro'),
        ),
    ]
