# Generated by Django 4.0.4 on 2023-01-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traslados',
            name='detalle',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
