# Generated by Django 4.2.7 on 2024-05-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_tramites_detalles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramites',
            name='detalles',
            field=models.CharField(max_length=200),
        ),
    ]
