# Generated by Django 4.2.7 on 2024-07-18 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_marcas_modelos_alter_activos_no_plaqueados_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidades',
            name='codigo',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
