# Generated by Django 4.0.4 on 2022-05-04 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_activos_plaqueados_tramite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activos_plaqueados',
            name='tramite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='activos', to='backend.tramites'),
        ),
        migrations.AlterField(
            model_name='tramites',
            name='referencia',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
