# Generated by Django 4.0.4 on 2023-01-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_traslados_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='activos_no_plaqueados',
            name='estado',
            field=models.CharField(choices=[('Deshecho', 'Deshecho'), ('En uso', 'En uso'), ('Funcional', 'Funcional'), ('Obsoleto', 'Obsoleto'), ('Obsoleto en revision', 'Obsoleto en revision'), ('Obsoleto en uso', 'Obsoleto en uso'), ('Obsoleto en repuesto', 'Obsoleto en repuesto'), ('Optimo', 'Optimo'), ('Proceso de deshecho', 'Proceso de deshecho'), ('Uso academico', 'Uso academico')], default='Optimo', max_length=25),
        ),
        migrations.AddField(
            model_name='activos_plaqueados',
            name='estado',
            field=models.CharField(choices=[('Deshecho', 'Deshecho'), ('En uso', 'En uso'), ('Funcional', 'Funcional'), ('Obsoleto', 'Obsoleto'), ('Obsoleto en revision', 'Obsoleto en revision'), ('Obsoleto en uso', 'Obsoleto en uso'), ('Obsoleto en repuesto', 'Obsoleto en repuesto'), ('Optimo', 'Optimo'), ('Proceso de deshecho', 'Proceso de deshecho'), ('Uso academico', 'Uso academico')], default='Optimo', max_length=25),
        ),
    ]
