# Generated by Django 4.0.4 on 2023-07-11 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_unidad_nombre_alter_activos_no_plaqueados_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activos_no_plaqueados',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.compra', verbose_name='Compra'),
        ),
        migrations.AlterField(
            model_name='activos_no_plaqueados',
            name='red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.red', verbose_name='Red'),
        ),
        migrations.AlterField(
            model_name='activos_no_plaqueados',
            name='serie',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Serie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activos_no_plaqueados',
            name='subtipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.subtipo', verbose_name='Subtipo'),
        ),
        migrations.AlterField(
            model_name='activos_no_plaqueados',
            name='tramites',
            field=models.ManyToManyField(null=True, to='backend.tramites', verbose_name='Tramites'),
        ),
        migrations.AlterField(
            model_name='activos_no_plaqueados',
            name='valor',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Valor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activos_plaqueados',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.compra', verbose_name='Compra'),
        ),
        migrations.AlterField(
            model_name='activos_plaqueados',
            name='red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.red', verbose_name='Red'),
        ),
        migrations.AlterField(
            model_name='activos_plaqueados',
            name='serie',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Serie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activos_plaqueados',
            name='subtipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.subtipo', verbose_name='Subtipo'),
        ),
        migrations.AlterField(
            model_name='activos_plaqueados',
            name='tramites',
            field=models.ManyToManyField(null=True, to='backend.tramites', verbose_name='Tramites'),
        ),
        migrations.AlterField(
            model_name='activos_plaqueados',
            name='valor',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Valor'),
            preserve_default=False,
        ),
    ]
