# Generated by Django 4.2.7 on 2024-07-21 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_unidades_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estados',
            name='descripcion',
            field=models.CharField(max_length=100, verbose_name='Descripción'),
        ),
    ]
