# Generated by Django 4.0.4 on 2023-11-15 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_activos_no_plaqueados_compra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(choices=[('Plaqueado', 'Plaqueado'), ('No plaqueado', 'No plaqueado'), ('Pendiente', 'Pendiente')], default='Plaqueado', max_length=13, verbose_name='Identificador')),
                ('placa', models.CharField(blank=True, max_length=30)),
                ('observacion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observación')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('marca', models.CharField(max_length=200, verbose_name='Marca')),
                ('valor', models.CharField(blank=True, max_length=200, verbose_name='Valor')),
                ('modelo', models.CharField(max_length=200, verbose_name='Modelo')),
                ('serie', models.CharField(blank=True, max_length=200, verbose_name='Serie')),
                ('garantia', models.DateField(null=True, verbose_name='Garantia')),
                ('fecha_ingreso', models.DateField(null=True, verbose_name='Fecha de Ingreso')),
                ('fecha_registro', models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('estado', models.CharField(choices=[(None, '--------'), ('Deshecho', 'Deshecho'), ('En uso', 'En uso'), ('Funcional', 'Funcional'), ('Obsoleto', 'Obsoleto'), ('Obsoleto en revision', 'Obsoleto en revision'), ('Obsoleto en uso', 'Obsoleto en uso'), ('Obsoleto en repuesto', 'Obsoleto en repuesto'), ('Optimo', 'Optimo'), ('Proceso de deshecho', 'Proceso de deshecho'), ('Uso academico', 'Uso academico')], default='Optimo', max_length=25, verbose_name='Estado')),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.compra', verbose_name='Compra')),
                ('red', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.red', verbose_name='Red')),
                ('subtipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.subtipo', verbose_name='Subtipo')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.tipo', verbose_name='Tipo')),
                ('tramites', models.ManyToManyField(blank=True, to='backend.tramites', verbose_name='Tramites')),
                ('ubicacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.ubicaciones', verbose_name='Ubicación')),
                ('ubicacion_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='anterior', to='backend.ubicaciones')),
            ],
        ),
        migrations.RemoveField(
            model_name='activos_plaqueados',
            name='compra',
        ),
        migrations.RemoveField(
            model_name='activos_plaqueados',
            name='red',
        ),
        migrations.RemoveField(
            model_name='activos_plaqueados',
            name='subtipo',
        ),
        migrations.RemoveField(
            model_name='activos_plaqueados',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='activos_plaqueados',
            name='tramites',
        ),
        migrations.RemoveField(
            model_name='activos_plaqueados',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='activos_plaqueados',
            name='ubicacion_anterior',
        ),
        migrations.DeleteModel(
            name='Activos_No_Plaqueados',
        ),
        migrations.DeleteModel(
            name='Activos_Plaqueados',
        ),
    ]
