# Generated by Django 4.0.4 on 2023-01-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_activos_no_plaqueados_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activos_no_plaqueados',
            name='tramite',
        ),
        migrations.RemoveField(
            model_name='activos_plaqueados',
            name='tramite',
        ),
        migrations.AddField(
            model_name='activos_no_plaqueados',
            name='tramites',
            field=models.ManyToManyField(to='backend.tramites'),
        ),
        migrations.AddField(
            model_name='activos_plaqueados',
            name='tramites',
            field=models.ManyToManyField(to='backend.tramites'),
        ),
    ]
