# Generated by Django 4.0.4 on 2022-05-07 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_tramites_recipiente_tramites_remitente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activos_plaqueados',
            name='serie',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='activos_plaqueados',
            name='tramite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos', to='backend.tramites'),
        ),
    ]
