# Generated by Django 4.0.4 on 2023-11-17 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_activos_remove_activos_plaqueados_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activos',
            name='observacion',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Observación'),
        ),
    ]
