# Generated by Django 4.0.4 on 2023-01-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_activos_no_plaqueados_tramite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traslados',
            name='detalle',
            field=models.CharField(default='', max_length=120),
        ),
    ]
