# Generated by Django 4.0.4 on 2023-01-10 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_traslados_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramites',
            name='recipiente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='backend.funcionarios'),
        ),
        migrations.AlterField(
            model_name='tramites',
            name='remitente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='backend.funcionarios'),
        ),
    ]
