# Generated by Django 4.0.4 on 2023-01-10 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_tramites_recipiente_alter_tramites_remitente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activos_no_plaqueados',
            name='subtipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.subtipo'),
        ),
        migrations.AlterField(
            model_name='activos_no_plaqueados',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.tipo'),
        ),
        migrations.AlterField(
            model_name='activos_plaqueados',
            name='subtipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.subtipo'),
        ),
        migrations.AlterField(
            model_name='activos_plaqueados',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.tipo'),
        ),
    ]
