# Generated by Django 4.2.7 on 2023-11-18 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_proveedor_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activos_No_Plaqueados',
            fields=[
                ('observacion', models.CharField(blank=True, max_length=500, null=True, verbose_name='Observación')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('marca', models.CharField(max_length=200, verbose_name='Marca')),
                ('valor', models.CharField(blank=True, max_length=200, verbose_name='Valor')),
                ('modelo', models.CharField(max_length=200, verbose_name='Modelo')),
                ('garantia', models.DateField(null=True, verbose_name='Garantia')),
                ('fecha_ingreso', models.DateField(null=True, verbose_name='Fecha de Ingreso')),
                ('fecha_registro', models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('estado', models.CharField(choices=[(None, '--------'), ('Deshecho', 'Deshecho'), ('En uso', 'En uso'), ('Funcional', 'Funcional'), ('Obsoleto', 'Obsoleto'), ('Obsoleto en revision', 'Obsoleto en revision'), ('Obsoleto en uso', 'Obsoleto en uso'), ('Obsoleto en repuesto', 'Obsoleto en repuesto'), ('Optimo', 'Optimo'), ('Proceso de deshecho', 'Proceso de deshecho'), ('Uso academico', 'Uso academico')], default='Optimo', max_length=25, verbose_name='Estado')),
                ('serie', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Activos No Plaqueados',
            },
        ),
        migrations.CreateModel(
            name='Activos_Plaqueados',
            fields=[
                ('observacion', models.CharField(blank=True, max_length=500, null=True, verbose_name='Observación')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('marca', models.CharField(max_length=200, verbose_name='Marca')),
                ('valor', models.CharField(blank=True, max_length=200, verbose_name='Valor')),
                ('modelo', models.CharField(max_length=200, verbose_name='Modelo')),
                ('garantia', models.DateField(null=True, verbose_name='Garantia')),
                ('fecha_ingreso', models.DateField(null=True, verbose_name='Fecha de Ingreso')),
                ('fecha_registro', models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('estado', models.CharField(choices=[(None, '--------'), ('Deshecho', 'Deshecho'), ('En uso', 'En uso'), ('Funcional', 'Funcional'), ('Obsoleto', 'Obsoleto'), ('Obsoleto en revision', 'Obsoleto en revision'), ('Obsoleto en uso', 'Obsoleto en uso'), ('Obsoleto en repuesto', 'Obsoleto en repuesto'), ('Optimo', 'Optimo'), ('Proceso de deshecho', 'Proceso de deshecho'), ('Uso academico', 'Uso academico')], default='Optimo', max_length=25, verbose_name='Estado')),
                ('placa', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('serie', models.CharField(blank=True, max_length=200, null=True, verbose_name='Serie')),
            ],
            options={
                'verbose_name_plural': 'Activos Plaqueados',
            },
        ),
        migrations.AlterModelOptions(
            name='compra',
            options={'verbose_name_plural': 'Compras'},
        ),
        migrations.AlterModelOptions(
            name='deshecho',
            options={'verbose_name_plural': 'Deshechos'},
        ),
        migrations.AlterModelOptions(
            name='permissions',
            options={'verbose_name_plural': 'Permissions'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='red',
            options={'verbose_name_plural': 'Red'},
        ),
        migrations.AlterModelOptions(
            name='subtipo',
            options={'verbose_name_plural': 'Subtipos'},
        ),
        migrations.AlterModelOptions(
            name='taller',
            options={'verbose_name_plural': 'Talleres'},
        ),
        migrations.AlterModelOptions(
            name='tipo',
            options={'verbose_name_plural': 'Tipos'},
        ),
        migrations.AlterModelOptions(
            name='tramites',
            options={'verbose_name_plural': 'Tramites'},
        ),
        migrations.AlterModelOptions(
            name='unidad',
            options={'verbose_name_plural': 'Unidades'},
        ),
        migrations.DeleteModel(
            name='Activos',
        ),
        migrations.AddField(
            model_name='activos_plaqueados',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.compra', verbose_name='Compra'),
        ),
        migrations.AddField(
            model_name='activos_plaqueados',
            name='red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.red', verbose_name='Red'),
        ),
        migrations.AddField(
            model_name='activos_plaqueados',
            name='subtipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.subtipo', verbose_name='Subtipo'),
        ),
        migrations.AddField(
            model_name='activos_plaqueados',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.tipo', verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='activos_plaqueados',
            name='tramites',
            field=models.ManyToManyField(blank=True, to='backend.tramites', verbose_name='Tramites'),
        ),
        migrations.AddField(
            model_name='activos_plaqueados',
            name='ubicacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.ubicaciones', verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='activos_plaqueados',
            name='ubicacion_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='plaqueados', to='backend.ubicaciones'),
        ),
        migrations.AddField(
            model_name='activos_no_plaqueados',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.compra', verbose_name='Compra'),
        ),
        migrations.AddField(
            model_name='activos_no_plaqueados',
            name='red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.red', verbose_name='Red'),
        ),
        migrations.AddField(
            model_name='activos_no_plaqueados',
            name='subtipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.subtipo', verbose_name='Subtipo'),
        ),
        migrations.AddField(
            model_name='activos_no_plaqueados',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.tipo', verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='activos_no_plaqueados',
            name='tramites',
            field=models.ManyToManyField(blank=True, to='backend.tramites', verbose_name='Tramites'),
        ),
        migrations.AddField(
            model_name='activos_no_plaqueados',
            name='ubicacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.ubicaciones', verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='activos_no_plaqueados',
            name='ubicacion_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='no_anterior', to='backend.ubicaciones'),
        ),
    ]
