# Generated by Django 4.0.4 on 2022-06-19 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_tramites_urgencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicaciones',
            name='lugar',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
