# Generated by Django 4.0.4 on 2022-06-20 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_ubicaciones_lugar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ubicaciones',
            options={'verbose_name_plural': 'Ubicaciones'},
        ),
        migrations.AlterField(
            model_name='traslados',
            name='activo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='backend.activos_plaqueados'),
        ),
    ]
