# Generated by Django 4.2.7 on 2023-11-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_activos_no_plaqueados_activos_plaqueados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activos_plaqueados',
            name='placa',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
