# Generated by Django 4.0.4 on 2022-06-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_ubicaciones_options_alter_traslados_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionarios',
            name='nombre_completo',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
