# Generated by Django 4.2.7 on 2023-12-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0008_alter_activos_plaqueados_placa"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activos_no_plaqueados",
            name="valor",
        ),
        migrations.RemoveField(
            model_name="activos_plaqueados",
            name="valor",
        ),
        migrations.AddField(
            model_name="activos_no_plaqueados",
            name="valor_colones",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="activos_no_plaqueados",
            name="valor_dolares",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="activos_plaqueados",
            name="valor_colones",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="activos_plaqueados",
            name="valor_dolares",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="activos_plaqueados",
            name="serie",
            field=models.CharField(
                blank=True, max_length=200, null=True, unique=True, verbose_name="Serie"
            ),
        ),
        migrations.AlterField(
            model_name="compra",
            name="numero_orden_compra",
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
