# Generated by Django 4.0.4 on 2022-06-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_funcionarios_nombre_completo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionarios',
            options={'verbose_name_plural': 'Funcionarios'},
        ),
        migrations.AlterField(
            model_name='tramites',
            name='detalles',
            field=models.CharField(max_length=900),
        ),
    ]
