# Generated by Django 4.0.4 on 2023-01-11 17:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_activos_no_plaqueados_observacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activos_no_plaqueados',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activos_plaqueados',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
