# Generated by Django 4.2.7 on 2023-12-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0010_alter_activos_no_plaqueados_marca_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activos_no_plaqueados",
            name="modelo",
            field=models.CharField(blank=True, max_length=200, verbose_name="Modelo"),
        ),
        migrations.AlterField(
            model_name="activos_plaqueados",
            name="modelo",
            field=models.CharField(blank=True, max_length=200, verbose_name="Modelo"),
        ),
    ]
