# Generated by Django 4.0.4 on 2022-07-12 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_funcionarios_options_alter_tramites_detalles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('lectura', 'puede ingresar a las vistas'), ('escritura', 'puede manipular datos por medio de las vistas')],
            },
        ),
        migrations.AlterModelOptions(
            name='traslados',
            options={'verbose_name_plural': 'Traslados'},
        ),
    ]
