# Generated by Django 4.0.4 on 2023-01-13 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_activos_no_plaqueados_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activos_no_plaqueados',
            name='ubicacion_anterior',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='no_plaqueados', to='backend.ubicaciones'),
        ),
        migrations.AddField(
            model_name='activos_plaqueados',
            name='ubicacion_anterior',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='plaqueado', to='backend.ubicaciones'),
        ),
    ]
