# Generated by Django 4.0.4 on 2023-01-13 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_activos_no_plaqueados_ubicacion_anterior_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activos_plaqueados',
            name='ubicacion_anterior',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='plaqueados', to='backend.ubicaciones'),
        ),
    ]
