# Generated by Django 4.2.7 on 2023-12-10 01:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0011_alter_activos_no_plaqueados_modelo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activos_plaqueados",
            name="serie",
            field=models.CharField(
                max_length=200, null=True, unique=True, verbose_name="Serie"
            ),
        ),
    ]
