# Generated by Django 4.0.4 on 2022-07-12 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_permissions_alter_traslados_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissions',
            options={'permissions': [('lectura', 'puede ingresar a las vistas'), ('escritura', 'puede manipular datos por medio de las vistas'), ('respaldos', 'puede respaldar la base de datos')]},
        ),
    ]
