# Generated by Django 4.0.4 on 2022-07-18 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_permissions_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activos_plaqueados',
            name='tramite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_sin_placa', to='backend.tramites'),
        ),
        migrations.CreateModel(
            name='Activos_No_Plaqueados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('detalle', models.CharField(max_length=300)),
                ('marca', models.CharField(max_length=200)),
                ('serie', models.CharField(max_length=200, null=True)),
                ('valor', models.CharField(max_length=200, null=True)),
                ('modelo', models.CharField(max_length=200)),
                ('garantia', models.DateField(null=True)),
                ('tramite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos', to='backend.tramites')),
                ('ubicacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.ubicaciones')),
            ],
        ),
    ]
