# Generated by Django 4.0.4 on 2023-01-13 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_activos_plaqueados_ubicacion_anterior'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.CharField(max_length=200)),
                ('beneficiario', models.CharField(max_length=200)),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.tramites')),
            ],
        ),
    ]
