# Generated by Django 4.0.4 on 2023-01-14 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_taller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deshecho',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='traslados',
            name='fecha',
        ),
    ]
