# Generated by Django 4.0.4 on 2022-07-26 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_activos_plaqueados_tramite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionarios',
            name='correo_institucional',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='correo_personal',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='telefono_oficina',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='telefono_personal',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='ubicaciones',
            name='sede',
            field=models.CharField(choices=[('Esparza', 'Sede de Esparza'), ('Cocal', 'Sede del Cocal')], default='Esparza', max_length=10),
        ),
    ]
