# Generated by Django 4.0.4 on 2023-01-14 22:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_remove_deshecho_fecha_remove_traslados_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='autor',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tramites',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
