# Generated by Django 4.0.4 on 2022-09-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_funcionarios_correo_institucional_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ubicaciones',
            old_name='lugar',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='ubicaciones',
            name='localizacion',
            field=models.CharField(default='NA', max_length=120),
        ),
    ]
