# Generated by Django 4.0.4 on 2023-01-15 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_taller_autor_alter_tramites_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Red',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MAC', models.CharField(blank=True, default='', max_length=45)),
                ('IP', models.CharField(blank=True, default='', max_length=20)),
                ('IP6', models.CharField(blank=True, default='', max_length=40)),
            ],
        ),
    ]
