# Generated by Django 4.0.4 on 2022-11-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_subtipo_tipo_activos_plaqueados_subtipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activos_plaqueados',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='activos_plaqueados',
            name='observacion',
            field=models.CharField(default='', max_length=300),
        ),
    ]
