# Generated by Django 4.0.4 on 2023-01-15 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_red'),
    ]

    operations = [
        migrations.AddField(
            model_name='activos_no_plaqueados',
            name='red',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.red'),
        ),
        migrations.AddField(
            model_name='activos_plaqueados',
            name='red',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.red'),
        ),
    ]
