# Generated by Django 4.0.4 on 2023-01-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_activos_no_plaqueados_red_activos_plaqueados_red'),
    ]

    operations = [
        migrations.AddField(
            model_name='red',
            name='IP_switch',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
