# Generated by Django 4.0.4 on 2022-11-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_activos_plaqueados_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activos_plaqueados',
            name='observacion',
            field=models.CharField(default='', max_length=300, null=True),
        ),
    ]
