# Generated by Django 4.0.4 on 2022-11-15 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_alter_activos_plaqueados_observacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deshecho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('activos_no_plaqueados', models.ManyToManyField(null=True, to='backend.activos_no_plaqueados')),
                ('activos_plaqueados', models.ManyToManyField(null=True, to='backend.activos_plaqueados')),
            ],
        ),
    ]
