# Generated by Django 4.0.4 on 2022-11-15 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_deshecho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deshecho',
            name='activos_no_plaqueados',
            field=models.ManyToManyField(to='backend.activos_no_plaqueados'),
        ),
        migrations.AlterField(
            model_name='deshecho',
            name='activos_plaqueados',
            field=models.ManyToManyField(to='backend.activos_plaqueados'),
        ),
    ]
