# Generated by Django 4.0.4 on 2022-11-15 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_alter_deshecho_activos_no_plaqueados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activos_no_plaqueados',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='activos_no_plaqueados',
            name='observacion',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='activos_no_plaqueados',
            name='subtipo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.subtipo'),
        ),
        migrations.AddField(
            model_name='activos_no_plaqueados',
            name='tipo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.tipo'),
        ),
        migrations.AlterField(
            model_name='activos_no_plaqueados',
            name='tramite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_sin_placa', to='backend.tramites'),
        ),
        migrations.AlterField(
            model_name='activos_plaqueados',
            name='tramite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.tramites'),
        ),
    ]
