# Generated by Django 4.0.4 on 2022-11-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_activos_no_plaqueados_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deshecho',
            name='referencia',
            field=models.CharField(default='', max_length=120, unique=True),
            preserve_default=False,
        ),
    ]
