# Generated by Django 4.0.4 on 2022-11-29 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_deshecho_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtipo',
            name='tipo',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.tipo'),
            preserve_default=False,
        ),
    ]
