# Generated by Django 4.0.4 on 2022-12-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_subtipo_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_solicitud', models.CharField(max_length=150)),
                ('origen_presupuesto', models.CharField(max_length=200)),
                ('decisión_final', models.CharField(max_length=100)),
                ('numero_procedimiento', models.CharField(max_length=120)),
                ('numero_factura', models.CharField(max_length=120)),
                ('proveedor', models.CharField(max_length=300)),
                ('telefono_proveedor', models.CharField(max_length=100)),
                ('correo_proveedor', models.CharField(max_length=120)),
            ],
        ),
    ]
