# Generated by Django 4.0.4 on 2023-01-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='id',
        ),
        migrations.AddField(
            model_name='compra',
            name='numero_orden_compra',
            field=models.CharField(default=1, max_length=15, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
