# Generated by Django 4.0.4 on 2023-01-04 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_remove_compra_id_compra_numero_orden_compra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activos_no_plaqueados',
            old_name='fecha',
            new_name='fecha_ingreso',
        ),
        migrations.RenameField(
            model_name='activos_plaqueados',
            old_name='fecha',
            new_name='fecha_ingreso',
        ),
        migrations.RenameField(
            model_name='ubicaciones',
            old_name='sede',
            new_name='instalacion',
        ),
        migrations.RenameField(
            model_name='ubicaciones',
            old_name='localizacion',
            new_name='ubicacion',
        ),
    ]
