# Generated by Django 4.0.4 on 2023-01-04 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_rename_fecha_activos_no_plaqueados_fecha_ingreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activos_no_plaqueados',
            name='tramite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.tramites'),
        ),
    ]
