# Generated by Django 4.0.4 on 2023-01-05 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_alter_activos_no_plaqueados_tramite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activos_no_plaqueados',
            name='detalle',
        ),
        migrations.RemoveField(
            model_name='activos_plaqueados',
            name='detalle',
        ),
        migrations.AlterField(
            model_name='activos_no_plaqueados',
            name='observacion',
            field=models.CharField(default='Observacion', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activos_plaqueados',
            name='observacion',
            field=models.CharField(default='Observacion', max_length=300),
            preserve_default=False,
        ),
    ]
